#ifndef DEEPBECKY_MOVEPICK_H
#define DEEPBECKY_MOVEPICK_H

// ============================================================
// MovePicker - Staged Move Ordering for Search
//
// Correctness model:
//   The legal move list is generated by Position::generateLegal()
//   (fully legal: handles pins, checks, en passant, castling). The
//   picker classifies those legal moves into stages and emits them
//   lazily. TT move, killers and counter-move are validated separately
//   by isPseudoLegal() (including the full MoveType) and legalMove()
//   before emission. Scoring, SEE filtering
//   and sorting are only paid for the moves actually consumed.
//
// Three modes:
//   MAIN_SEARCH - full ordering with TT, captures, killers, quiets
//   QSEARCH     - captures only (+ all evasions when in check)
//   PROBCUT     - captures with SEE >= threshold
// ============================================================

#include "position.h"

// ========================= MovePicker Class =========================
struct MovePicker {
    // Picker mode determines which stages are used
    enum class Mode { MAIN_SEARCH, QSEARCH, PROBCUT };

    // Construction for normal search
    MovePicker(Position& position, const Move& ttMove, SearchStack* searchStack, int depth,
               const Move& killer0, const Move& killer1,
               const Move& counterMove);

    // Construction for quiescence search
    MovePicker(Position& position, const Move& ttMove, bool inCheck, int ply = 0);

    // Construction for ProbCut (captures with SEE >= threshold)
    MovePicker(Position& position, const Move& ttMove, int seeThreshold, int ply = 0);

    // Get next move in order. Returns MOVE_NONE when exhausted.
    Move next();

    // Skip remaining quiet moves (for late move pruning).
    void skipQuiets();

    // SEE>=0 status of the move just returned by next(). Lets the search
    // reuse the SEE(m, 0) already paid in GOOD_CAPTURES/BAD_CAPTURES instead
    // of recomputing it. UNKNOWN means the caller must evaluate it itself.
    enum class SeeStatus { UNKNOWN, NO, YES };
    SeeStatus lastSeeStatus() const { return lastSee; }

private:
    Position& pos;
    Move ttMove;
    SearchStack* ss = nullptr;
    int ply = 0;

    // Capture move storage (good + bad)
    Move* captures = nullptr;
    int*  captureScores = nullptr;
    int   captureCount = 0;
    int   captureIdx = 0;

    // Bad captures deferred from GOOD_CAPTURES stage
    Move* badCaptures = nullptr;
    int*  badScores = nullptr;
    int   badCount = 0;
    int   badIdx = 0;

    // Quiet move storage
    Move* quiets = nullptr;
    int*  quietScores = nullptr;
    int   quietCount = 0;
    int   quietIdx = 0;

    // Killers and counter-move (full flags + king-safety validation)
    Move killer0, killer1;
    Move counterMove;

    // ProbCut SEE threshold
    int probcutThreshold = 0;

    // State
    bool quietsSkipped = false;
    bool inCheckQs = false;

    // SEE>=0 status of the last move emitted by next() (see lastSeeStatus()).
    SeeStatus lastSee = SeeStatus::UNKNOWN;

    enum class Stage {
        // Main search stages
        TT_MOVE,
        CAPTURE_INIT,
        GOOD_CAPTURES,
        KILLER_0,
        KILLER_1,
        COUNTER_MOVE,
        QUIET_INIT,
        QUIETS,
        BAD_CAPTURES,
        // QSearch stages
        QS_TT_MOVE,
        QS_CAPTURE_INIT,
        QS_CAPTURES,
        QS_EVASION_INIT,
        QS_EVASIONS,
        // ProbCut stages
        PC_TT_MOVE,
        PC_CAPTURE_INIT,
        PC_CAPTURES,
        // Terminal
        DONE
    } stage;

    // Score captures with MVV-LVA + capture history
    void scoreCaptures();

    // Score quiet moves with history heuristics
    void scoreQuiets();

    // Selection sort over a list: pick best from [idx..count) and swap to idx.
    Move selectBest(Move* list, int* scores, int count, int& idx);


};

#endif // DEEPBECKY_MOVEPICK_H
